# Generated by Django 6.0.7 on 2026-07-14 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('college_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('home_address', models.TextField()),
                ('current_residence', models.TextField()),
                ('course', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=10)),
                ('roll_no', models.CharField(max_length=30, unique=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('backlogs', models.PositiveIntegerField(default=0)),
                ('tenth_percentage', models.CharField(blank=True, max_length=10)),
                ('twelfth_percentage', models.CharField(blank=True, max_length=10)),
                ('achievements', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
