# Generated by Django 6.0.7 on 2026-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
