# Generated by Django 6.0.7 on 2026-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_semester_percentage',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_course',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_percentage',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_education_gap',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='has_internship_experience',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hometown_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='internship_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_year_of_passing',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelfth_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='twelfth_year_of_passing',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
