# Generated by Django 6.0.7 on 2026-07-26 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_current_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('resume', 'Resume'), ('aadhar', 'Aadhar Card'), ('tenth_marksheet', '10th Marksheet'), ('twelfth_marksheet', '12th Marksheet')], max_length=20)),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
