# Generated by Django 6.0.7 on 2026-07-27 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
