# Generated by Django 6.0.7 on 2026-07-28 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remark_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Resume', max_length=150)),
                ('template', models.CharField(default='classic', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_drafts', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
