# Generated by Django 6.0.7 on 2026-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_resumedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='announcements_last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
