# Generated by Django 6.0.7 on 2026-08-10 05:57

import uuid
from django.db import migrations, models


def generate_unique_tokens(apps, schema_editor):
    StudentProfile = apps.get_model("students", "StudentProfile")
    for profile in StudentProfile.objects.all():
        profile.invite_token = uuid.uuid4()
        profile.save(update_fields=["invite_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentprofile_announcements_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='registration_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentprofile',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]