# Generated by Django 6.0.7 on 2026-08-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentprofile_invite_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('aadhar', 'Aadhar Card'), ('tenth_marksheet', '10th Marksheet'), ('twelfth_marksheet', '12th Marksheet'), ('certificate', 'Certificate')], max_length=20),
        ),
    ]
