# Generated by Django 6.0.7 on 2026-07-14 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Applied', max_length=25)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drive_type', models.CharField(choices=[('Final Placements', 'Final Placements'), ('Internship', 'Internship'), ('Pre-Placement Offer', 'Pre-Placement Offer')], default='Final Placements', max_length=30)),
                ('company_name', models.CharField(max_length=150)),
                ('company_website', models.URLField(blank=True)),
                ('jd_link', models.URLField(blank=True)),
                ('profiles_offered', models.JSONField(default=list)),
                ('job_location', models.CharField(max_length=150)),
                ('eligible_courses', models.JSONField(default=list)),
                ('eligible_batches', models.JSONField(default=list)),
                ('ctc', models.CharField(max_length=100)),
                ('bond', models.CharField(default='No Bond', max_length=100)),
                ('process_details', models.CharField(blank=True, max_length=255)),
                ('last_date_of_application', models.DateTimeField()),
                ('application_link', models.URLField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
