# Generated by Django 6.0.7 on 2026-07-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='pm_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='secondary_application_link',
            field=models.URLField(blank=True),
        ),
    ]
