# Generated by Django 6.0.7 on 2026-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_drive_pm_note_drive_secondary_application_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='drive_type',
            field=models.CharField(default='Final Placements', help_text='e.g. Final Placements, Internship, Internship with PPO, Pre-Placement Offer', max_length=50),
        ),
    ]
