# Generated by Django 6.0.7 on 2026-07-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_alter_drive_drive_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='secondary_application_link',
            new_name='company_link',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='application_link',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='bond',
        ),
        migrations.AddField(
            model_name='application',
            name='aadhar_file',
            field=models.FileField(default='', upload_to='applications/aadhar/%Y/%m/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='aadhar_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='campus_name',
            field=models.CharField(choices=[('SAITM, Gurgaon', 'SAITM, Gurgaon'), ('SAITM, Delhi', 'SAITM, Delhi')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file',
            field=models.FileField(default='', upload_to='applications/resumes/%Y/%m/'),
            preserve_default=False,
        ),
    ]
