# Generated by Django 6.0.7 on 2026-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0005_rename_secondary_application_link_drive_company_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='jd_link',
        ),
        migrations.RemoveField(
            model_name='drive',
            name='profiles_offered',
        ),
        migrations.AddField(
            model_name='drive',
            name='jd_text',
            field=models.TextField(blank=True),
        ),
    ]
