# Generated by Django 6.0.7 on 2026-07-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_remove_drive_jd_link_remove_drive_profiles_offered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='profiles_offered',
            field=models.JSONField(default=list),
        ),
    ]
