# Generated by Django 6.0.7 on 2026-07-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0007_drive_profiles_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tenth_marksheet_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/tenth_marksheet/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='application',
            name='twelfth_marksheet_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/twelfth_marksheet/%Y/%m/'),
        ),
    ]
