# Generated by Django 6.0.7 on 2026-07-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0008_application_tenth_marksheet_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='tenth_marksheet_file',
        ),
        migrations.RemoveField(
            model_name='application',
            name='twelfth_marksheet_file',
        ),
    ]
