# Generated by Django 6.0.7 on 2026-08-17 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0010_resumesampletemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveJDFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='drive_jd_files/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_files', to='placements.drive')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
